# Generated by Django 5.0.6 on 2024-09-26 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("translate_native", "Перевод с родного языка"),
                            ("choose_translation", "Выбор правильного перевода"),
                            ("fill_in_blanks", "Заполнение пропусков"),
                            ("match_image", "Сопоставление слова и изображения"),
                            ("audio_test", "Аудио-тест"),
                            ("spell_word", "Правописание слова"),
                            ("define_word", "Определение слова"),
                            ("sort_by_meaning", "Сортировка по значению"),
                            ("word_cascade", "Словесный каскад"),
                            ("flashcards", "Карточки"),
                            ("crossword", "Кроссворд"),
                            ("find_word", "Найди слово"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="WordLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("A1", "Beginner (A1)"),
                            ("A2", "Elementary (A2)"),
                            ("B1", "Intermediate (B1)"),
                            ("B2", "Upper-Intermediate (B2)"),
                            ("C1", "Advanced (C1)"),
                            ("C2", "Proficient (C2)"),
                        ],
                        max_length=2,
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("success", models.BooleanField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_learn.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_learn.word",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="word",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base_learn.wordlevel"
            ),
        ),
        migrations.CreateModel(
            name="UserExerciseRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(default=0)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_learn.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "exercise")},
            },
        ),
        migrations.CreateModel(
            name="UserWordProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_learn", "Need to learn"),
                            ("learning", "Learning"),
                            ("learned", "Learned"),
                        ],
                        default="to_learn",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_learn.word",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "word")},
            },
        ),
    ]
