# Generated by Django 5.0.6 on 2024-09-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_learn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="word_type",
            field=models.CharField(default="unknown", max_length=50),
            preserve_default=False,
        ),
    ]
